var AlertConstants = {
  INVALID_LOGIN: "INVALID_LOGIN",
  LOG_OUT: "LOG_OUT",
  BOARD_NOT_FOUND: "BOARD_NOT_FOUND",
  BLANK_TITLE: "BLANK_TITLE",
  NOTE_SENT: "NOTE_SENT",
  BOARD_DELETED: "BOARD_DELETED"
};

module.exports = AlertConstants;
