var BoardConstants = {
  ALL_BOARDS_RECEIVED: "ALL_BOARDS_RECEIVED",
  SINGLE_BOARD_RECEIVED: "SINGLE_BOARD_RECEIVED",
  ALL_LISTS_RECEIVED: "LISTS_FOR_BOARD_RECEIVED",
  SINGLE_LIST_RECEIVED: "SINGLE_LIST_FOR_BOARD_RECEIVED"
};

module.exports = BoardConstants;
