// var ListConstants = {
// 	ALL_LISTS_RECEIVED: "ALL_LISTS_RECEIVED",
//   SINGLE_LIST_RECEIVED: "SINGLE_LIST_RECEIVED",
//   ALL_CARDS_RECEIVED: "ALL_CARDS_FOR_LIST_RECEIVED",
//   SINGLE_CARD_RECEIVED: "SINGLE_CARD_FOR_LIST_RECEIVED"
// };
//
// module.exports = ListConstants;
