var ListConstants = {
	ALL_LISTS_RECEIVED: "ALL_LISTS_RECEIVED",
  SINGLE_LIST_RECEIVED: "SINGLE_LIST_RECEIVED",
  ALL_CARDS_RECEIVED: "ALL_CARDS_RECEIVED",
  SINGLE_CARD_RECEIVED: "SINGLE_CARD_RECEIVED"
};

module.exports = ListConstants;
